<?php
/**
 * Created by PhpStorm.
 * User: eugeniy
 * Date: 24.12.17
 * Time: 10:08
 */

    require_once "zs_index/SiteheaderPage.class.php";

    class ShearchPage extends SiteHeader {

        // Нужен для запроса
        private $helpquery;

        // Нужен для запроса
        private $helpresult;

        // Количество вернутых сторк
        private $reusultrowcount;

        // Тут находятся результаты поиска
        private $searchresults;

        // Тут находится резултаты поиска
        private $searchstring;

        // Для запроса
        private $babestring;

        private function PrepareResultTable()
        {
            if ($this->searchstring != "")
            {
                $searchwords = explode(" ", strtolower($this->searchstring));

                foreach ($searchwords as $pointer)
                {
                    $this->babestring .= "(ProductName LIKE '%". $pointer . "%') AND ";
                }

                $this->babestring .= ' 1';


                $this->helpquery = $this->database->prepare("SELECT COUNT(*) FROM SearchResultTable WHERE ". $this->babestring, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
                $this->helpquery->execute();
                $this->reusultrowcount = $this->helpquery->fetch()[0];

                $this->query = $this->database->prepare("SELECT * FROM SearchResultTable WHERE ". $this->babestring, array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
                $this->query->execute();

                // IW.ShowwindowId, IW.ShowwindowProductsId, P.ProductId, P.ProductName, P.Price, P.PictureURL
                while ($this->result = $this->query->fetch(PDO::FETCH_NUM, PDO::FETCH_ORI_NEXT))
                {
                    $this->smarty->assign('ginsw', $this->result[0]);
                    $this->smarty->assign('name', $this->result[2]);
                    $this->smarty->assign('price', $this->result[3]);
                    $this->smarty->assign('image', $this->result[4]);

                    $productid = $this->result[1];
                    $attrstring = "";

                    $this->helpquery = $this->database->prepare("SELECT * FROM SearchGetProductAttributes WHERE ProductId = :Id AND Important = 1", array(PDO::ATTR_CURSOR => PDO::CURSOR_SCROLL));
                    $this->helpquery->bindParam(":Id", $productid);
                    $this->helpquery->execute();

                    // PAName, Value, ProductId
                    while ($this->helpresult = $this->helpquery->fetch(PDO::FETCH_NUM, PDO::FETCH_ORI_NEXT))
                    {
                        $attrstring .= '<tr><td>'. $this->helpresult[0]. ':</td><td style="vertical-align: middle;"><span class="label label-danger">'. $this->helpresult[1].'</span></td></tr>';
                    }

                    $this->smarty->assign('attrs', $attrstring);

                    $this->searchresults .= $this->smarty->fetch("shearch-product.tpl");
                }
            }
        }

        private function Build()
        {
            $this->smarty->assign('rescount', $this->reusultrowcount);
            $this->smarty->assign('results', $this->searchresults);

            return $this->smarty->fetch("shearch.tpl");
        }

        public function Draw()
        {
            parent::Draw($this->Build()); // TODO: Change the autogenerated stub
        }

        public function __construct($searchstr)
        {
            parent::__construct("Результат поиска");

            $this->searchstring = $searchstr;

            $this->PrepareResultTable();
        }
    }
?>