<?php
/**
 * Created by PhpStorm.
 * User: eugeniy
 * Date: 28.12.17
 * Time: 7:43
 */

    require_once 'zs_admin/AdminheaderPage.class.php';

    class AdminLogsPage extends AdminHeaderPage
    {
        private $logstable;

        private function PrepareLogsTable()
        {
            $this->query = $this->database->prepare("SELECT * FROM AdminShopLogs ORDER BY CreateDate DESC");
            $this->query->execute();

            while ($this->result = $this->query->fetch(PDO::FETCH_NUM, PDO::FETCH_ORI_NEXT))
            {
                $this->smarty->assign("id", $this->result[0]);
                $this->smarty->assign("date", $this->result[1]);
                $this->smarty->assign("name", $this->result[2]);

                $this->logstable .= $this->smarty->fetch("logs-table.tpl");
            }
        }
        public function Draw()
        {
            $this->smarty->assign("logstable", $this->logstable);

            parent::Draw($this->smarty->fetch("logs.tpl")); // TODO: Change the autogenerated stub
        }

        public function __construct()
        {
            parent::__construct("Logs", AdminHeaderPage::ADM_EDITPAGE_OTHER);

            $this->PrepareLogsTable();
        }
    }

?>